#!/bin/bash
pwd
sed -i "s/isProductionBuild = false/isProductionBuild = true/g" ./src/index.js # toggle production build to disable redux middleware
x=$(git log -1 --format=%aI)
sed -i "s/TIMESTAMP/$x/g" ./public/index.html
HASH=$(git rev-parse HEAD)
sed -i "s/LGCH/$HASH/g" ./public/index.html
npm run build
sed -i 's|/static|./static|g' ./build/index.html 
git checkout -- ./public/index.html
git checkout -- ./src/index.js
