#!/bin/bash

# this is the script to publish this TTAP app to Surge.sh
./scripts/transpile

# First, we build the app
./scripts/build

# Then, run surge to publish
surge --domain https://ttap.surge.sh --project ./build