#!/bin/bash 
# Clear the screen
clear 

# Clean the output directory
DIRECTORY="src/core"
if [ -d "$DIRECTORY" ]; then
    # Control will enter here if $DIRECTORY exists.
    echo "Cleaning output directory . . ."
    rm -r src/core*
fi

# Transpile TS into JS
ts_compiler_version=$(./node_modules/typescript/bin/tsc -v)
echo "Transpling TypeScript files into JavaScript (using TSCompiler $ts_compiler_version ). . . "
output=$(./node_modules/typescript/bin/tsc -p ./ts/tsconfig.json)

# Check if output contain error
if [[ $output == *"error"* ]]; 
then
    echo -e "\e[31mBuild failed due to the following errors: "
    echo "$output"
    exit 1
else # Signify success
    echo -e "\e[32m "
    echo "███████╗ ██╗   ██╗  ██████╗  ██████╗ ███████╗ ███████╗ ███████╗ ██╗"
    echo "██╔════╝ ██║   ██║ ██╔════╝ ██╔════╝ ██╔════╝ ██╔════╝ ██╔════╝ ██║"
    echo "███████╗ ██║   ██║ ██║      ██║      █████╗   ███████╗ ███████╗ ██║"
    echo "╚════██║ ██║   ██║ ██║      ██║      ██╔══╝   ╚════██║ ╚════██║ ╚═╝"
    echo "███████║ ╚██████╔╝ ╚██████╗ ╚██████╗ ███████╗ ███████║ ███████║ ██╗"
    echo "╚══════╝  ╚═════╝   ╚═════╝  ╚═════╝ ╚══════╝ ╚══════╝ ╚══════╝ ╚═╝"
    echo -e "\e[39mThe output files are located at: \e[35m src/core"
    echo -e "\e[39mTo run unit test, type: \e[33m npm run test"
    echo -e "\e[39mTo edit the build output, edit \e[34m transpile"
    echo " "
fi


# Refer the following link for colors and formatting in bash
# https://misc.flogisoft.com/bash/tip_colors_and_formatting

